version: '3'

services:

        abebox_db:
                image: mysql:latest
                container_name: abebox_db
                restart: always
                ports:
                        - "3306:3306"
                environment:
                        MYSQL_DATABASE: abebox
                        MYSQL_ROOT_USER: root
                        MYSQL_ROOT_PASSWORD: abebox
                volumes:
                        #- ./sql/abebox_db.sql:/docker-entrypoint-initdb.d/init.sql
                        - ./dbs/abebox_db:/var/lib/mysql
                networks:
                        abebox_network:
                                ipv4_address: 172.25.0.3

        abebox_webserver:
                build:
                        context: .
                        dockerfile: ABEbox_Dockerfile
                image: abebox_webserver
                container_name: abebox_webserver
                depends_on:
                        - abebox_db
                ports:
                        - "5002:5002"
                networks:
                        abebox_network:
                                ipv4_address: 172.25.0.2

networks:
        abebox_network:
                driver: bridge
                ipam:
                        config:
                                - subnet: 172.25.0.0/16

volumes:
        persistent: